name: Maven CI # Name of the workflow

on: # When to run the workflow
    push:   # Run the workflow on push
        branches:
            - master
    pull_request:   # Run the workflow on pull request
        branches:
            - master

jobs: # List of jobs
    build:  # Job name, it can be any name

        runs-on: ubuntu-latest # where the job will run

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
            - run: echo "💡 The ${{ github.sha }} commit has been checked out."
            - run: echo "💡 The ${{ github.actor }} actor is running the workflow."

            - run: | # Run multiple commands
                echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
                echo "💡 The ${{ github.sha }} commit has been checked out."
                echo "💡 The ${{ github.actor }} actor is running the workflow."


            - uses: actions/setup-java@v4
              with:
                  distribution: 'zulu'
                  java-version: '17'


            # use artifact caching to speed up the build
            - uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
                  restore-keys: |
                      ${{ runner.os }}-gradle-

            - name: Build with gradle
              run: ./gradlew build


    unit-test:
        runs-on: ubuntu-latest
        needs:
            - build
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - run: echo run unit tests
            #run unit tests
            - name: Run unit tests
              run: ./gradlew test
